# encoding: utf-8

list_animals = ["aardvark", "babuíno", "cabra", "doninha", "elefante", "falcão", "gaivota", "hamster", "iaque", "jacaré",
                "kouprey", "lagarta", "macaco", "naja", "ocapi", "panda gigante", "quati", "raposa", "salamandra",
                "tarsius", "uapiti", "veado", "wallaby", "xajá", "yak", "zebra", "abelha", "baleia", "cação",
                "dragão-de-komodo", "enguia", "foca", "ganso", "hiena", "iguana", "jaguar", "kakapo", "lagarto",
                "medusa", "nambu", "Órix", "panda vermelho", "quatimirim", "ratazana", "sapo", "tartaruga", "urso",
                "vespa", "weimaraner", "xangó", "ynambu", "zabelê", "abutre", "barata", "camelo", "dugongo", "Équidnas",
                "formiga", "garça-real", "hipopótamo", "íbex", "javali", "kea", "lagosta", "morcego", "nandaia", "ostra",
                "pantera", "quatipuru", "rato", "serpente", "tatu", "uacari", "vespão", "wombat", "xará", "yorkshire",
                "zangão", "ácaro", "bisão", "canguru", "damão", "esquilo", "frango", "gato", "hadoque", "íbis", "jabiru",
                "kinguio", "leão", "morsa", "narceja", "ouriço", "papa-formigas", "quebra-nozes", "rena", "suricata",
                "tentilhão", "unau", "vison", "xarelete", "zaragateiro", "Águia", "boi", "cão", "dançador",
                "estrela-do-mar", "fuinha", "gauro", "harpia", "iguanara", "jabuti", "kiwi", "leão do mar", "mosca",
                "narval", "ovelha", "pato", "quebra-ossos", "quebra-osso", "rinoceronte", "sabiá", "texugo", "unha-longa",
                "vaca", "xaréu", "zarro", "albatroz", "borboleta", "caracol", "degolado", "égua", "furão", "gazela", "hírax",
                "impala", "jaçanã", "koala", "lebre", "mosquito", "náutilo", "ocapi", "pato-real", "queixada", "rouxinol",
                "sagui", "tigre", "unicórnio", "vaca-marinha", "xaru", "zebra", "alce", "búfalo africano", "caranguejo",
                "degu", "elefante-marinho", "faisão", "gerbilo", "indicador", "jacu", "kookaburra", "lémure", "mula",
                "negrinho", "olho-de-boi", "pavão", "quem-te-vestiu", "rã", "salamandra", "toupeira", "urso panda",
                "vaga-lume", "vagalume", "xauim", "zebu", "alpaca", "búfalo americano", "carneiro", "diablotim", "ema",
                "ferreirinho", "girafa", "indri", "jacupará", "kowari", "leopardo", "musaranho", "neon", "onça", "pega",
                "quero-quero", "rabudinho", "salmão", "tubarão", "urso", "veado", "xero", "zidedê", "anaconda", "burro",
                "castor", "diabo-da-tasmânia", "enchova", "flamingo", "gnu", "inhacoso", "jamanta", "krill", "lhama",
                "macaco", "nhacundá", "orangotango", "peixe-boi", "quetzal", "raia", "sanguessuga", "tainha", "uru",
                "verdilhão", "xexéu", "zombeteiro", "anchova", "bacalhau", "cavalo", "diamante-de-gould", "enferrujado",
                "flautim", "golfinho", "inhala", "jararaca", "kudu", "libélula", "mamute", "nhandiá", "orca", "pelicano",
                "quiriquiri", "raposa", "sapo", "tamanduá", "urubu", "verdinho", "ximango", "zorrilho", "andorinha",
                "bacuri", "cefo", "dingo", "enho", "fossa", "gorila", "inhambu", "jegue", "lobo", "manatim", "niala",
                "órix", "perdiz", "ratazana", "sardão", "tamboril", "urutaurana", "vespa", "ximburé", "anta", "badejo",
                "chacal", "dinossauro", "escaravelho", "fraca-da-guiné", "guanaco", "irapuã", "jiboia", "lontra",
                "mandril", "niquim", "ornitorrinco", "perú", "rato", "sardinha", "tapir", "urutu", "víbora", "xixarro",
                "antílope", "bagre", "chimpanzé", "dodô", "escorpião", "frango-d'água", "guaxinim", "irara", "joaninha",
                "loris", "mangangá", "noitibó", "osga", "piolho", "rêmora", "saúva", "tarântula", "vieira", "xofrango",
                "aranha", "baiacu", "cisne", "dourado", "escrevedeira", "freirinha", "gafanhoto", "iratim",
                "joão-de-barro", "lula", "maracanã", "numbat", "ostra", "pomba", "rena", "seriema", "tartaruga",
                "vira-bosta ", "xuri", "ave-lira", "barbo", "cobra", "dragão-do-banhado", "esmerilhão", "galinha",
                "itapema", "jumento", "lacraia", "marimbondo", "nútria", "otária", "pombo", "rendeira", "serpente",
                "tatu", "vison", "avestruz", "barracuda", "coelho", "dragão-voador", "espadarte", "galo", "lagartixa",
                "mariposa", "ouriço", "pónei", "rinoceronte", "siri", "tatuí", "vitela", "arara", "beija-flor", "coiote",
                "dromedário", "esponja", "gambá", "lampreia", "marisco", "ouriço-do-mar", "porco", "robalo", "suçuarana",
                "tentilhão", "viúva", "asno", "besouro", "cormorão", "esturjão", "gamo", "lavadeira", "marmota", "ovelha",
                "porco-espinho", "rouxinol", "sucuri", "tetra", "viúva-negra", "atum", "bem-te-vi", "coruja",
                "estorninho", "garça", "lavagante", "marreco", "porquinho-da-índia", "suiriri", "texugo", "bezerro",
                "corvo", "garoupa", "leão-marinho", "marta", "puma", "suricate", "tico-tico", "bicho-da-seda", "cupim",
                "gavião", "lebre", "massarongo", "panda", "surubi", "tigre", "bisonte", "cotovia", "geco", "lêmure",
                "medusa", "pantera", "surucucu", "tilápia", "boa", "crocodilo", "gerbo", "leopardo", "melro", "papagaio",
                "tordo", "bode", "cudu", "gibão", "lesma", "mergulhão", "pardal", "tororó", "boto", "cachalote", "girino",
                "lhama", "merluza", "pássaro", "toupeira", "cachorro", "gralha", "libélula", "mexilhão", "pato", "touro",
                "cágado", "grifo", "lince", "mico", "pavão", "tritão", "camaleão", "grilo", "linguado", "milhafre",
                "peixe", "truta", "camarão", "grou", "lobo", "mineirinho", "peixe-boi", "tubarão", "camundongo", "guará",
                "lombriga", "minhoca", "pelicano", "tucano", "canário", " lontra", "mocho", "percevejo", "tucuxi",
                "capivara", " lula", "mono", "perereca,carrapato", " morcego", "periquito", "cascavel", " moreia",
                "pernilongo", "cavalo-marinho", " morsa", "peru", "cegonha", " mosca", "pescada", " centopeia",
                "mosquito", "pica-pau", "chinchila", "muçurana", "pinguim", "chita", " mula", "piolho", " cigarra",
                "musaranho", "piranha", " coala", " pirarucu", "codorna", " polvo", "cutia", " pombo", "pônei",
                "porco", "porco-espinho", "porquinho-da-índia", "preá", "preguiça", "pulga", "Aardvark", "Babuíno",
                "Cabra", "Doninha", "Elefante", "Falcão", "Gaivota", "Hamster", "Iaque", "Jacaré",
                "Kouprey", "Lagarta", "Macaco", "Naja", "Ocapi", "Panda gigante", "Quati", "Raposa", "Salamandra",
                "Tarsius", "Uapiti", "Veado", "Wallaby", "Xajá", "Yak", "Zebra", "Abelha", "Baleia", "Cação",
                "Dragão-de-komodo", "Enguia", "Foca", "Ganso", "Hiena", "Iguana", "Jaguar", "Kakapo", "Lagarto",
                "Medusa", "Nambu", "Órix", "Panda vermelho", "Quatimirim", "Ratazana", "Sapo", "Tartaruga", "Urso",
                "Vespa", "Weimaraner", "Xangó", "Ynambu", "Zabelê", "Abutre", "Barata", "Camelo", "Dugongo", "Équidnas",
                "Formiga", "Garça-real", "Hipopótamo", "íbex", "Javali", "Kea", "Lagosta", "Morcego", "Nandaia", "Ostra",
                "Pantera", "Quatipuru", "Rato", "Serpente", "Tatu", "Uacari", "Vespão", "Wombat", "Xará", "Yorkshire",
                "Zangão", "ácaro", "Bisão", "Canguru", "Damão", "Esquilo", "Frango", "Gato", "Hadoque", "íbis", "Jabiru",
                "Kinguio", "Leão", "Morsa", "Narceja", "Ouriço", "Papa-formigas", "Quebra-nozes", "Rena", "Suricata",
                "Tentilhão", "Unau", "Vison", "Xarelete", "Zaragateiro", "Águia", "Boi", "Cão", "Dançador",
                "Estrela-do-mar", "Fuinha", "Gauro", "Harpia", "Iguanara", "Jabuti", "Kiwi", "Leão do mar", "Mosca",
                "Narval", "Ovelha", "Pato", "Quebra-ossos", "Quebra-osso", "Rinoceronte", "Sabiá", "Texugo", "Unha-longa",
                "Vaca", "Xaréu", "Zarro", "Albatroz", "Borboleta", "Caracol", "Degolado", "égua", "Furão", "Gazela", "Hírax",
                "Impala", "Jaçanã", "Koala", "Lebre", "Mosquito", "Náutilo", "Ocapi", "Pato-real", "Queixada", "Rouxinol",
                "Sagui", "Tigre", "Unicórnio", "Vaca-marinha", "Xaru", "Zebra", "Alce", "Búfalo africano", "Caranguejo",
                "Degu", "Elefante-marinho", "Faisão", "Gerbilo", "Indicador", "Jacu", "Kookaburra", "Lémure", "Mula",
                "Negrinho", "Olho-de-boi", "Pavão", "Quem-te-vestiu", "Rã", "Salamandra", "Toupeira", "Urso panda",
                "Vaga-lume", "vagalume", "Xauim", "Zebu", "Alpaca", "Búfalo americano", "Carneiro", "Diablotim", "Ema",
                "Ferreirinho", "Girafa", "Indri", "Jacupará", "Kowari", "Leopardo", "Musaranho", "Neon", "Onça", "Pega",
                "Quero-quero", "Rabudinho", "Salmão", "Tubarão", "Urso", "Veado", "Xero", "Zidedê", "Anaconda", "Burro",
                "Castor", "Diabo-da-tasmânia", "Enchova", "Flamingo", "Gnu", "Inhacoso", "Jamanta", "Krill", "Lhama",
                "Macaco", "Nhacundá", "Orangotango", "Peixe-boi", "Quetzal", "Raia", "Sanguessuga", "Tainha", "Uru",
                "Verdilhão", "Xexéu", "Zombeteiro", "Anchova", "Bacalhau", "Cavalo", "Diamante-de-gould", "Enferrujado",
                "Flautim", "Golfinho", "Inhala", "Jararaca", "Kudu", "Libélula", "Mamute", "Nhandiá", "Orca", "Pelicano",
                "Quiriquiri", "Raposa", "Sapo", "Tamanduá", "Urubu", "Verdinho", "Ximango", "Zorrilho", "Andorinha",
                "Bacuri", "Cefo", "Dingo", "Enho", "Fossa", "Gorila", "Inhambu", "Jegue", "Lobo", "Manatim", "Niala",
                "órix", "Perdiz", "Ratazana", "Sardão", "Tamboril", "Urutaurana", "Vespa", "Ximburé", "Anta", "Badejo",
                "Chacal", "Dinossauro", "Escaravelho", "Fraca-da-guiné", "Guanaco", "Irapuã", "Jiboia", "Lontra",
                "Mandril", "Niquim", "Ornitorrinco", "Perú", "Rato", "Sardinha", "Tapir", "Urutu", "Víbora", "Xixarro",
                "Antílope", "Bagre", "Chimpanzé", "Dodô", "Escorpião", "Frango-d'água", "Guaxinim", "Irara", "Joaninha",
                "Loris", "Mangangá", "Noitibó", "Osga", "Piolho", "Rêmora", "Saúva", "Tarântula", "Vieira", "Xofrango",
                "Aranha", "Baiacu", "Cisne", "Dourado", "Escrevedeira", "Freirinha", "Gafanhoto", "Iratim",
                "João-de-barro", "Lula", "Maracanã", "Numbat", "Ostra", "Pomba", "Rena", "Seriema", "Tartaruga",
                "Vira-bosta ", "Xuri", "Ave-lira", "Barbo", "Cobra", "Dragão-do-banhado", "Esmerilhão", "Galinha",
                "Itapema", "Jumento", "Lacraia", "Marimbondo", "Nútria", "Otária", "Pombo", "Rendeira", "Serpente",
                "Tatu", "Vison", "Avestruz", "Barracuda", "Coelho", "Dragão-voador", "Espadarte", "Galo", "Lagartixa",
                "Mariposa", "Ouriço", "Pónei", "Rinoceronte", "Siri", "Tatuí", "Vitela", "Arara", "Beija-flor", "Coiote",
                "Dromedário", "Esponja", "Gambá", "Lampreia", "Marisco", "Ouriço-do-mar", "Porco", "Robalo", "Suçuarana",
                "Tentilhão", "Viúva", "Asno", "Besouro", "Cormorão", "Esturjão", "Gamo", "Lavadeira", "Marmota", "Ovelha",
                "Porco-espinho", "Rouxinol", "Sucuri", "Tetra", "Viúva-negra", "Atum", "Bem-te-vi", "Coruja",
                "Estorninho", "Garça", "Lavagante", "Marreco", "Porquinho-da-índia", "Suiriri", "Texugo", "Bezerro",
                "Corvo", "Garoupa", "Leão-marinho", "Marta", "Puma", "Suricate", "Tico-tico", "Bicho-da-seda", "Cupim",
                "Gavião", "Lebre", "Massarongo", "Panda", "Surubi", "Tigre", "Bisonte", "Cotovia", "Geco", "Lêmure",
                "Medusa", "Pantera", "Surucucu", "Tilápia", "Boa", "Crocodilo", "Gerbo", "Leopardo", "Melro", "Papagaio",
                "Tordo", "Bode", "Cudu", "Gibão", "Lesma", "Mergulhão", "Pardal", "Tororó", "Boto", "Cachalote", "Girino",
                "Lhama", "Merluza", "Pássaro", "Toupeira", "Cachorro", "Gralha", "Libélula", "Mexilhão", "Pato", "Touro",
                "Cágado", "Grifo", "Lince", "Mico", "Pavão", "Tritão", "Camaleão", "Grilo", "Linguado", "Milhafre",
                "Peixe", "Truta", "Camarão", "Grou", "Lobo", "Mineirinho", "Peixe-boi", "Tubarão", "Camundongo", "Guará",
                "Lombriga", "Minhoca", "Pelicano", "Tucano", "Canário", " lontra", "Mocho", "Percevejo", "Tucuxi",
                "Capivara", " lula", "Mono", "Perereca,carrapato", " morcego", "Periquito", "Cascavel", " moreia",
                "Pernilongo", "Cavalo-marinho", " morsa", "Peru", "Cegonha", " mosca", "Pescada", " centopeia",
                "Mosquito", "Pica-pau", "Chinchila", "Muçurana", "Pinguim", "Chita", " mula", "Piolho", " cigarra",
                "Musaranho", "Piranha", " coala", " pirarucu", "Codorna", " polvo", "Cutia", " pombo", "Pônei",
                "Porco", "Porco-espinho", "Porquinho-da-índia", "Preá", "Preguiça", "Pulga", "guepardo", "Guepardo",
                "passarinho", "Passarinho", "umbrella"]


def convertStr2SignedInt(data):

    signedData = []
    ind = 0
    for i in range(0, len(data) / 2):
        signedData.append(data[ind] + data[ind + 1] * 256)
        ind = ind + 2

    for i in range(0, len(signedData)):
        if signedData[i] >= 32768:
            signedData[i] = signedData[i] - 65536

    for i in range(0, len(signedData)):
        signedData[i] = signedData[i] / 32768.0

    return signedData