# Generated by Django 3.0.5 on 2020-04-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('genre', models.CharField(max_length=100)),
                ('study', models.IntegerField()),
                ('results', models.TextField()),
            ],
        ),
    ]
