# Generated by Django 3.0.5 on 2020-04-28 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exams',
            old_name='genre',
            new_name='genero',
        ),
        migrations.RenameField(
            model_name='exams',
            old_name='age',
            new_name='idade',
        ),
        migrations.RenameField(
            model_name='exams',
            old_name='patient',
            new_name='paciente',
        ),
        migrations.RenameField(
            model_name='exams',
            old_name='results',
            new_name='resultados',
        ),
        migrations.RenameField(
            model_name='exams',
            old_name='study',
            new_name='tempo_estudo',
        ),
    ]
