# Generated by Django 3.0.5 on 2020-05-07 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0002_auto_20200506_1624'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
