# Generated by Django 3.0.5 on 2020-05-15 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0003_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='exame',
            name='nota',
            field=models.IntegerField(default=0),
        ),
    ]
