# Generated by Django 3.0.5 on 2020-05-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0004_exame_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='exame',
            name='transcri',
            field=models.TextField(default=None),
        ),
    ]
