# Generated by Django 3.0.5 on 2020-05-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0005_exame_transcri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exame',
            name='transcri',
            field=models.TextField(),
        ),
    ]
