# Generated by Django 3.0.5 on 2020-05-21 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0007_exame_audio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exame',
            name='audio',
        ),
    ]
