# Generated by Django 3.0.5 on 2020-05-29 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0008_remove_exame_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='exame',
            name='audioRecorded',
            field=models.FileField(default=None, upload_to='media/'),
        ),
    ]
