# Generated by Django 3.0.5 on 2020-07-07 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0010_auto_20200529_2053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exame',
            old_name='paciente',
            new_name='nome_completo',
        ),
        migrations.RenameField(
            model_name='exame',
            old_name='tempo_estudo',
            new_name='tempo_de_estudo',
        ),
    ]
