# Generated by Django 3.0.5 on 2020-07-07 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0011_auto_20200707_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exame',
            name='genero',
            field=models.CharField(choices=[('feminino', 'feminino'), ('masculino', 'masculino')], max_length=100),
        ),
    ]
